const BLOQUES=[
{t:"Los programas",d:"Dos cosas que quedaron abiertas de la última vez.",qs:[
 {id:"p1",q:"Ahora que existe <b>Lifestyle</b> (mantenimiento), ¿qué pasa con <b>Personalizado</b>?",
  o:["Lifestyle reemplaza a Personalizado. Quedan 7 programas.",
     "Son 8 programas: los 7 de ahora más Lifestyle.",
     "Otra cosa — te la escribo abajo."]},
 {id:"p2",q:"El banco de alimentos que ya me pasaste, ¿sirve igual para los otros programas mientras los defines?",
  o:["Sí. El mismo banco para todos; lo que cambia son las calorías y la proteína del día.",
     "No. Cada programa necesita su propio banco y te los voy pasando uno por uno.",
     "Para algunos sí y para otros no — te digo cuáles abajo."]},
]},
{t:"Cómo se arma el día",d:"Esta parte es la que más necesito. Sin esto no puedo armar un menú.",qs:[
 {id:"p3",q:"¿Cómo quieres que la app ofrezca las comidas?",
  o:["Siempre 5 comidas + 2 snacks.",
     "Siempre 3 comidas (los snacks se juntan con las comidas).",
     "Que la persona elija entre las dos.",
     "Depende del programa — te digo abajo."]},
 {id:"p4",q:"<b>El reparto del día.</b> Tomando el Plan 1 como ejemplo (3 proteínas, 3 vegetales, 2 frutas, 2 almidones, 1 cucharada de grasa y 2 licuados), ¿cuál se parece más a como tú lo harías?",
  o:["<b>Opción A</b> — Desayuno: 1 proteína + 1 almidón · Snack: 1 fruta · Comida: 1 proteína + 2 vegetales + 1 almidón · Snack: 1 fruta · Cena: 1 proteína + 1 vegetal. Los licuados entre comidas.",
     "<b>Opción B</b> — Desayuno: 1 proteína + 1 fruta · Snack: 1 licuado · Comida: 1 proteína + 2 vegetales + 1 almidón · Snack: 1 fruta + 1 licuado · Cena: 1 proteína + 1 vegetal + 1 almidón.",
     "Ninguna de las dos. Te escribo abajo cómo debe ser."]},
 {id:"p5",q:"El licuado de proteína, ¿cuenta como una de las proteínas del día o va aparte?",
  o:["Cuenta como una de las proteínas del día.",
     "Va aparte, es adicional.",
     "Depende — te explico abajo."]},
 {id:"p6",q:"Las combinaciones vegetarianas (frijol + arroz, lenteja + elote, avena + crema de cacahuate), ¿gastan también una selección de almidón?",
  o:["No. Solo cuentan como una proteína.",
     "Sí. Cuentan como proteína y también como almidón.",
     "Otra — te explico abajo."]},
 {id:"p7",q:"La leche extra del Plan 2 (4 oz) y del Plan 4 (8 oz), ¿va contra el tope de 3 lácteos por semana?",
  o:["No, es adicional a los 3.",
     "Sí, cuenta dentro de los 3.",
     "Otra — te explico abajo."]},
 {id:"p8",q:"Los licuados que marca cada plan (2 en Plan 1 y 2, 3 en Plan 3 y 4), ¿son <b>por día</b> o <b>por semana</b>?",
  o:["Por día.","Por semana.","Otra — te explico abajo."]},
]},
{t:"A quién le toca cada nivel",d:"Para que el sistema asigne el Plan 1, 2, 3 o 4 solo.",qs:[
 {id:"p9",q:"Ejercicio. En el algoritmo, hacer ejercicio 3 o más veces por semana manda a Plan 3. Pero dijiste que ya empezado el plan solo se cambia si pasa de 5 veces. ¿Está bien así?",
  o:["Sí: al entrar son 3 o más, y ya empezado solo cambia si pasa de 5.",
     "No, debe ser el mismo número en los dos momentos — te digo cuál abajo.",
     "Otra — te explico abajo."]},
 {id:"p10",q:"Hoy la presión alta, la gota y los anticonceptivos solo suben de nivel a las mujeres. ¿Un hombre con presión alta o gota también debe subir a Plan 2?",
  o:["Sí, aplica igual para hombres.",
     "No, solo para mujeres.",
     "Presión y gota sí; anticonceptivos obviamente no."]},
 {id:"p11",q:"Cuando la persona va bajando de peso, ¿se le recalculan las calorías?",
  o:["No. El plan se queda con los números del inicio.",
     "Sí, cada 4 semanas con el peso nuevo.",
     "Sí, cuando baja cierto porcentaje — te digo cuánto abajo."]},
]},
{t:"Seguridad",d:"Esto es para no hacerle daño a nadie. Si algo no te parece, dímelo sin filtro.",qs:[
 {id:"p12",q:"<b>Meta de peso.</b> Hoy la app propone bajar el 10% del peso actual, y nunca deja poner una meta por debajo de un IMC de 20. ¿Está bien?",
  o:["Sí, así está bien.",
     "El 10% está bien, pero el piso debe ser otro — te digo cuál abajo.",
     "La meta la debe poner la persona, no la app.",
     "Otra — te explico abajo."]},
 {id:"p13",q:"<b>Embarazo.</b> Ya quedó que no hacemos plan de pérdida de peso y que pueden ir a Lifestyle. Para ese caso, ¿qué hay que quitar del banco de alimentos?",
  m:true,
  o:["Pescado alto en mercurio","Mariscos crudos","Quesos sin pasteurizar","Hígado",
     "Nada, el banco sirve igual","Otra cosa — te digo abajo"]},
 {id:"p14",q:"Si alguien dice que <b>vive o vivió con un trastorno de la conducta alimentaria</b>, hoy la app le quita la meta de peso y los premios por libras, pero le entrega el plan igual. ¿Está bien?",
  o:["Sí, así está bien.",
     "No debería recibir plan; mejor que nos escriba.",
     "Sí, pero además quiero que me avisen de ese caso.",
     "Otra — te explico abajo."]},
 {id:"p15",q:"<b>Insulina o hipoglucemia.</b> Hoy sale un aviso de hablar con su médico, pero el plan se entrega igual. ¿Está bien?",
  o:["Sí, así está bien.",
     "No, ese caso lo quiero revisar yo antes de que reciba el plan.",
     "Otra — te explico abajo."]},
]},
{t:"Premios",d:"La app ya tiene la mecánica; falta saber qué estás dispuesta a dar.",qs:[
 {id:"p16",q:"Cada cierto avance la app entrega un premio. ¿Cuáles sí?",
  m:true,
  o:["Un mensaje tuyo","Un video corto tuyo","Descuento en el Kit","Una llamada 1 a 1","Ninguno por ahora"]},
]},
];
